name: Pull Request Review Assignment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
    - name: Assign Reviewer
      run: |
        branch_name=$(echo ${{ github.head_ref }} | awk -F'/' '{print $2}')
        reviewers=""
        
        if [ "$branch_name" == "main" ]; then
          reviewers="pawan"
        elif [ "$branch_name" == "release" ]; then
          # No specific reviewer required for the release branch
          exit 0
        elif [[ "$branch_name" == feature/* ]]; then
          reviewers="rahul"
        fi

        if [ -n "$reviewers" ]; then
          echo "Reviewers: $reviewers"
          gh pr request-reviewers -R ${{ github.repository }} -B $branch_name $reviewers
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
